In [64]:
# DataFrame的创建方式
import pandas as pd
import numpy as np
from pandas.conftest import ascending

# 通过series创建
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
df = pd.DataFrame({'第1列': s1, '第2列': s2})
print(df)
print(type(df))  #<class 'pandas.DataFrame'>
print(type(df['第1列']))  # <class 'pandas.Series'>

# 通过字典来创建
dict1 = {
    'name': ['zhangsan', 'lisi', 'andy', 'wangwu', 'alice'],
    'age': [15, 16, 17, 27, 30],
    'score': [90, 80, 80, 60, 50]
}
# 可以通过参数设置索引和列名（column是列标签）
df = pd.DataFrame(dict1, index=[1, 2, 3, 4, 5], columns=['name', 'age', 'score'])
print(df)

   第1列  第2列
0    1    6
1    2    7
2    3    8
3    4    9
4    5   10
<class 'pandas.DataFrame'>
<class 'pandas.Series'>
       name  age  score
1  zhangsan   15     90
2      lisi   16     80
3      andy   17     80
4    wangwu   27     60
5     alice   30     50

In [19]:
# DataFrame的属性
print('行索引', df.index)  #Index([1, 2, 3, 4, 5], dtype='int64') # Index(['name', 'age', 'score'], dtype='str')
print('列标签', df.columns)
print(df.values)

行索引 Index([1, 2, 3, 4, 5], dtype='int64')
列标签 Index(['name', 'age', 'score'], dtype='str')
[['zhangsan' 15 90]
 ['lisi' 16 80]
 ['andy' 17 70]
 ['wangwu' 27 60]
 ['alice' 30 50]]

In [23]:
print('维度', df.ndim)
print('数据类型', df.dtypes)
print('形状：', df.shape)
print('个数', df.size)

维度 2
数据类型 name       str
age      int64
score    int64
dtype: object
形状： (5, 3)
个数 15

In [25]:
# 行列转置
# print(df.T)
# print(df.T.index)
# print(df.T.values)

              1     2     3       4      5
name   zhangsan  lisi  andy  wangwu  alice
age          15    16    17      27     30
score        90    80    70      60     50
Index(['name', 'age', 'score'], dtype='str')
[['zhangsan' 'lisi' 'andy' 'wangwu' 'alice']
 [15 16 17 27 30]
 [90 80 70 60 50]]

In [28]:
# 获取元素 loc iloc at  iat
# 获取某行
print(df)
print(df.loc[4])  # 显示索引获取了第四行的数据
print(df.iloc[3])  # 隐式索引获取

       name  age  score
1  zhangsan   15     90
2      lisi   16     80
3      andy   17     70
4    wangwu   27     60
5     alice   30     50
name     wangwu
age          27
score        60
Name: 4, dtype: object
name     alice
age         30
score       50
Name: 5, dtype: object

In [29]:
# 获取某列
print(df.loc[:, 'name'])  # 显示获取
print(df.iloc[:, 0])  # 隐式获取
print(df.iloc[:, :])  # 切片操作

1    zhangsan
2        lisi
3        andy
4      wangwu
5       alice
Name: name, dtype: str
1    zhangsan
2        lisi
3        andy
4      wangwu
5       alice
Name: name, dtype: str
       name  age  score
1  zhangsan   15     90
2      lisi   16     80
3      andy   17     70
4    wangwu   27     60
5     alice   30     50

In [33]:
# 获取单个元素
print(df)
print(df.at[3, 'score'])
print(df.iat[3, 2])
print(df.loc[3, 'score'])
print(df.iloc[3, 2])

       name  age  score
1  zhangsan   15     90
2      lisi   16     80
3      andy   17     70
4    wangwu   27     60
5     alice   30     50
70
60
70
60

In [38]:
# 获取单列数据
print(df['name'])
print(type(df['name']))  # <class 'pandas.Series'>
print(df.name)  # Name: name, dtype: str
print(df[['name']])
print(type(df[['name']]))  # <class 'pandas.DataFrame'>

1    zhangsan
2        lisi
3        andy
4      wangwu
5       alice
Name: name, dtype: str
<class 'pandas.Series'>
1    zhangsan
2        lisi
3        andy
4      wangwu
5       alice
Name: name, dtype: str
       name
1  zhangsan
2      lisi
3      andy
4    wangwu
5     alice
<class 'pandas.DataFrame'>

In [ ]:
# 多列数据的获取
print(df[['name', 'score']])

In [41]:
# 查看部分数据
print(df.head(2))
print(df.tail(2))

       name  age  score
1  zhangsan   15     90
2      lisi   16     80
     name  age  score
4  wangwu   27     60
5   alice   30     50

In [47]:
# 布尔索引进行筛选
df.score > 70
df[(df.score > 70) & (df.age <= 20)]
# 多个条件

       name  age  score
1  zhangsan   15     90
2      lisi   16     80

In [48]:
# 随机抽样
df.sample(3)  # 可以接受参数，默认取全部

     name  age  score
4  wangwu   27     60
5   alice   30     50
2    lisi   16     80

In [51]:
print(df.isin(['andy', 20]))  # 查看元素是否包含在参数集合中

    name    age  score
1  False  False  False
2  False  False  False
3   True  False  False
4  False  False  False
5  False  False  False

In [52]:
print(df.isna())  # 查看是否是缺失值

    name    age  score
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [57]:
print(df.score.sum())  # 一般是用来求某一列的总和
print(df.score.mean())  # 平均数
print(df.score.std())  # 方差
print(df.score.median())  # 中位数
print(df.score.var())
print(df.score.min())
print(df.score.max())
print(df.score.quantile(q=0.9))  # 分位数

350
70.0
15.811388300841896
70.0
250.0
50
90
86.0

In [58]:
# 去重:没有重复的就不去
print(df.drop_duplicates())

       name  age  score
1  zhangsan   15     90
2      lisi   16     80
3      andy   17     70
4    wangwu   27     60
5     alice   30     50

In [66]:
# 检查是否有重复的
print(df.duplicated(subset=['score']))

1    False
2    False
3     True
4    False
5    False
dtype: bool

In [67]:
# 随机采样
df.sample(2)
df

       name  age  score
1  zhangsan   15     90
2      lisi   16     80
3      andy   17     80
4    wangwu   27     60
5     alice   30     50

In [68]:
# 替换
print(df.replace(15, 55))

       name  age  score
1  zhangsan   55     90
2      lisi   16     80
3      andy   17     80
4    wangwu   27     60
5     alice   30     50

In [71]:
df.cumsum()  # 默认按照列来累积，可以通过参数更改
df.cummin(axis=0)

       name  age  score
1  zhangsan   15     90
2      lisi   15     80
3      andy   15     80
4      andy   15     60
5     alice   15     50

In [72]:
# 排序
print(df.sort_index(ascending=False))

       name  age  score
5     alice   30     50
4    wangwu   27     60
3      andy   17     80
2      lisi   16     80
1  zhangsan   15     90

In [75]:
print(df.sort_values(by=['score', 'age'], ascending=[False, True]))

       name  age  score
1  zhangsan   15     90
2      lisi   16     80
3      andy   17     80
4    wangwu   27     60
5     alice   30     50

In [76]:
df.nlargest(2, columns=['score', 'age'])  #最大值两个
df.nsmallest(2, columns=['score', 'age'])  # 最小值两个

       name  age  score
1  zhangsan   15     90
3      andy   17     80

In [91]:
'''
案例1：学生成绩分析

场景：某班级的学生成绩数据如下，请完成以下任务：

1.计算每位学生的总分和平均分。

2.找出数学成绩高于90分或英语成绩高于85分的学生。

3.按总分从高到低排序，并输出前3名学生。


'''
import pandas as pd

data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '数学': [85, 92, 78, 88, 95],
    '英语': [90, 88, 85, 92, 80],
    '物理': [75, 80, 88, 85, 90]
}
scores = pd.DataFrame(data)
scores

# 1.计算每位学生的总分和平均分。
# 总分行数据相加
scores['总分']=scores[['数学','英语','物理']].sum(axis=1)
scores


# 2.找出数学成绩高于90分或英语成绩高于85分的学生。
# 布尔索引
# scores[(scores.数学 >90) | (scores.英语 > 85)]


# 3.按总分从高到低排序，并输出前3名学生。
# nlargest(3)
scores.sort_values('总分', ascending=False).head(3)
scores.nlargest(n=3,columns='总分')

   姓名  数学  英语  物理   总分
3  赵六  88  92  85  265
4  钱七  95  80  90  265
1  李四  92  88  80  260

In [98]:
'''

案例2：销售数据分析

场景：某公司销售数据如下，请完成以下任务：
1. 计算每种产品的总销售额（销售额 = 单价 × 销量）。
2. 找出销售额最高的产品。
3. 按销售额从高到低排序，并输出所有产品信息。

'''

import pandas as pd

data = {
    '产品名称': ['A', 'B', 'C', 'D'],
    '单价': [100, 150, 200, 120],
    '销量': [50, 30, 20, 40]
}

df = pd.DataFrame(data)
df
# 1. 计算每种产品的总销售额（销售额 = 单价 × 销量）。
df['销售额'] = df['单价'] * df['销量']
df
# 2. 找出销售额最高的产品。
df.nlargest(1,'销售额')

# 3. 按销售额从高到低排序，并输出所有产品信息。
df.sort_values('销售额', ascending=False)

  产品名称   单价  销量   销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000

In [119]:
'''

案例3：电商用户行为分析

场景：某电商平台的用户行为数据如下，请完成以下任务：

1. 计算每位用户的总消费金额（消费金额 = 商品单价 × 购买数量）

2. 找出消费金额最高的用户，并输出其所有信息

3. 计算所有用户的平均消费金额（保留2位小数）

4. 统计电子产品的总购买数量

'''

import pandas as pd

data = {
    '用户ID': [101, 102, 103, 104, 105],
    '用户名': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    '商品类别': ['电子产品', '服饰', '电子产品', '家居', '服饰'],
    '商品单价': [1200, 300, 800, 150, 200],
    '购买数量': [1, 3, 2, 5, 4]
}

df = pd.DataFrame(data)

# 1. 计算每位用户的总消费金额（消费金额 = 商品单价 × 购买数量）
df['总消费金额'] = df['商品单价'] * df['购买数量']
df
# 2. 找出消费金额最高的用户，并输出其所有信息
print(df.nlargest(1,columns='总消费金额'))
# 3. 计算所有用户的平均消费金额（保留2位小数）
df['总消费金额'].mean()
# 4. 统计电子产品的总购买数量
df[df['商品类别']=='电子产品']['购买数量'].sum() #np.int64(3)

   用户ID      用户名  商品类别  商品单价  购买数量  总消费金额
2   103  Charlie  电子产品   800     2   1600

np.int64(3)