In [9]:
# 数据的导入
import pandas as pd

df = pd.read_csv('data/employees.csv')
# df
print(type(df))  # <class 'pandas.DataFrame'>
print(df.head())
print(df.tail())
print(df.salary.mean())

# 数据的导出
df = df.head()
df.to_csv('data/new-employees.csv')

<class 'pandas.DataFrame'>
   employee_id first_name last_name     email  phone_number   job_id   salary  \
0          100     Steven      King     SKING  515.123.4567  AD_PRES  24000.0
1          101      N_ann   Kochhar  NKOCHHAR  515.123.4568    AD_VP  17000.0
2          102        Lex   De Haan   LDEHAAN  515.123.4569    AD_VP  17000.0
3          103  Alexander    Hunold   AHUNOLD  590.423.4567  IT_PROG   9000.0
4          104      Bruce     Ernst    BERNST  590.423.4568  IT_PROG   6000.0

   commission_pct  manager_id  department_id
0             NaN         NaN           90.0
1             NaN       100.0           90.0
2             NaN       100.0           90.0
3             NaN       102.0           60.0
4             NaN       103.0           60.0
     employee_id first_name last_name     email  phone_number      job_id  \
102          202        Pat       Fay      PFAY  603.123.6666      MK_REP
103          203      Susan    Mavris   SMAVRIS  515.123.7777      HR_REP
104          204    Hermann      Baer     HBAER  515.123.8888      PR_REP
105          205    Shelley   Higgins  SHIGGINS  515.123.8080      AC_MGR
106          206    William     Gietz    WGIETZ  515.123.8181  AC_ACCOUNT

      salary  commission_pct  manager_id  department_id
102   6000.0             NaN       201.0           20.0
103   6500.0             NaN       101.0           40.0
104  10000.0             NaN       101.0           70.0
105  12000.0             NaN       101.0          110.0
106   8300.0             NaN       205.0          110.0
6461.682242990654

In [19]:
# json数据
df = pd.read_json('data/data1.json')
df
# print(type(df))  # <class 'pandas.DataFrame'>

# 读取复杂的json数据
import json

with open('data/test.json') as f:
    data = json.load(f)

# print(data)
# print(type(data))
df = pd.DataFrame(data['users'])
df

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

In [43]:
# 缺失值的处理
# nan:not a number
# None:
import pandas as pd
import numpy as np

s = pd.Series([1, 2, np.nan, None, pd.NA])
print(s)
df = pd.DataFrame([[12, 23, pd.NA], [7, 8, 9], [10, None, 12]], columns=['第一列', '第二列', '第三列'])

# 查看是否是缺失值
# print(s.isna())
# print(s.isnull())
# print(df.isna())
#
# print(df.isna().sum()) # 查看缺失值的个数
# print(df.isnull())

# 剔除缺失值
print(s.dropna())
print('*' * 30)
print(df)
print(df.dropna())  # 只要是有缺失值，会删除一整条的记录
# 可以写条件
print('*' * 30)
print(df.dropna(how='all'))  # 只有全部都是缺失值才会删除
print(df.dropna(thresh=2))  # 参数：至少有n个值不是缺失值，就保留
print(df.dropna(thresh=3))  # 参数：至少有n个值不是缺失值，就保留
print(df.dropna(axis=1))  # 剔除一整列的记录
print(df.dropna(subset=['第一列']))  # 指定去剔除指定列

# 填充缺失值
df = pd.read_csv('data/weather_withna.csv')
df.tail()
df.isna().sum(axis=0)
df.head()
print(df.fillna({'temp_max': 20, 'wind': 2.5}))  # 使用字典来填充

print(df.fillna({'wind': df['wind'].mean()}))  # 使用统计值来填充

# 根据缺失值附近的值进行填充
print(df.ffill().tail())  # 用前面的相邻值填充
print(df.bfill().tail())  # 用后面的相邻值填充

0       1
1       2
2     NaN
3    None
4    <NA>
dtype: object
0    1
1    2
dtype: object
******************************
   第一列   第二列   第三列
0   12  23.0  <NA>
1    7   8.0     9
2   10   NaN    12
   第一列  第二列 第三列
1    7  8.0   9
******************************
   第一列   第二列   第三列
0   12  23.0  <NA>
1    7   8.0     9
2   10   NaN    12
   第一列   第二列   第三列
0   12  23.0  <NA>
1    7   8.0     9
2   10   NaN    12
   第一列  第二列 第三列
1    7  8.0   9
   第一列
0   12
1    7
2   10
   第一列   第二列   第三列
0   12  23.0  <NA>
1    7   8.0     9
2   10   NaN    12
            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            NaN      20.0       NaN   2.5      NaN
1457  2015-12-28            NaN      20.0       NaN   2.5      NaN
1458  2015-12-29            NaN      20.0       NaN   2.5      NaN
1459  2015-12-30            NaN      20.0       NaN   2.5      NaN
1460  2015-12-31           20.6      12.2       5.0   3.8     rain

[1461 rows x 6 columns]
            date  precipitation  temp_max  temp_min      wind  weather
0     2012-01-01            0.0      12.8       5.0  4.700000  drizzle
1     2012-01-02           10.9      10.6       2.8  4.500000     rain
2     2012-01-03            0.8      11.7       7.2  2.300000     rain
3     2012-01-04           20.3      12.2       5.6  4.700000     rain
4     2012-01-05            1.3       8.9       2.8  6.100000     rain
...          ...            ...       ...       ...       ...      ...
1456  2015-12-27            NaN       NaN       NaN  3.242055      NaN
1457  2015-12-28            NaN       NaN       NaN  3.242055      NaN
1458  2015-12-29            NaN       NaN       NaN  3.242055      NaN
1459  2015-12-30            NaN       NaN       NaN  3.242055      NaN
1460  2015-12-31           20.6      12.2       5.0  3.800000     rain

[1461 rows x 6 columns]
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [45]:
# 数据类型转换

import pandas as pd

data = {
    "name": ["alice", "alice", "bob", "alice", "jack", "bob"],
    "age": [26, 25, 30, 25, 35, 30],
    'city': ['NY', 'NY', 'LA', 'NY', 'SF', 'LA']
}

df = pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [49]:
# 检查重复
df.duplicated()  # 一整条记录都是一样的，标记为重复，返回True
df.drop_duplicates()  # 去掉完全重复的
df.drop_duplicates(subset=['name'])  # 根据指定列去掉重复
df.drop_duplicates(subset=['name'], keep='last')  #保留最新出现的行

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [50]:
# 数据类型的转换
df = pd.read_csv('data/sleep.csv')
df.dtypes

person_id                    int64
gender                         str
age                          int64
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [51]:
df['age'] = df['age'].astype('int16')
df.dtypes

person_id                    int64
gender                         str
age                          int16
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [52]:
df['gender'] = df['gender'].astype('category')  # 分类
df.dtypes

person_id                     int64
gender                     category
age                           int16
occupation                      str
sleep_duration              float64
sleep_quality               float64
physical_activity_level       int64
stress_level                  int64
bmi_category                    str
blood_pressure                  str
heart_rate                    int64
daily_steps                   int64
sleep_disorder                  str
dtype: object

In [54]:
# 使用map函数处理
df['is_male'] = df['gender'].map({'Female': True, 'Male': False})  # 分类
df.is_male

0      False
1       True
2      False
3      False
4      False
       ...
395     True
396     True
397     True
398     True
399    False
Name: is_male, Length: 400, dtype: category
Categories (2, bool): [True, False]

In [61]:
# 数据变形
import pandas as pd

data = {
    'ID': [1, 2],
    'name': ['alice', 'bob'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df = pd.DataFrame(data)
df.T  # 行列转置
'''
1 alice math 90
2 alice math 85
3 alice math 95
'''
# 宽表转换成长表
df2 = pd.melt(df, id_vars=['ID', 'name'], var_name='科目', value_name='分数')
df.sort_values('name')
print(df2)
# 长表转换成宽表
pd.pivot(df2, index=['ID', 'name'], columns='科目', values='分数')

   ID   name       科目  分数
0   1  alice     Math  90
1   2    bob     Math  85
2   1  alice  English  88
3   2    bob  English  92
4   1  alice  Science  95
5   2    bob  Science  89

科目        English  Math  Science
ID name
1  alice       88    90       95
2  bob         92    85       89

In [123]:
import pandas as pd

data = {
    'ID': [1, 2],
    'name': ['alice smith', 'bob andy'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df = pd.DataFrame(data)
df
# 分列操作
df[['first', 'last']] = df['name'].str.split(" ", expand=True)
df

'''
在 pandas 中，df['列名'] 与 df[['列名']] 的区别在于返回的数据结构：

df['列名']：返回一个 Series（一维带标签的数组）。

df[['列名']]：返回一个 DataFrame（二维表格），即使只有一列。
'''

# 导入文件
df = pd.read_csv('data/sleep.csv')
# 分列
df = df[['person_id', 'blood_pressure']]
df[['high', 'low']] = df['blood_pressure'].str.split('/', expand=True)
df.info
# 数据类型转换
df['high'] = df['high'].astype('int64')
df['low'] = df['low'].astype('int64')
df.high.mean()

np.float64(122.19)

In [77]:
# 数据分箱 pd.cut(x,bins,labels)
import pandas as pd

df = pd.read_csv('data/employees.csv')
df.head()
# 对salary进行处理
df1 = df.head(10)[['employee_id', 'salary']]
df1

   employee_id   salary
0          100  24000.0
1          101  17000.0
2          102  17000.0
3          103   9000.0
4          104   6000.0
5          105   4800.0
6          106   4800.0
7          107   4200.0
8          108  12000.0
9          109   9000.0

In [82]:
# bins = n ,分成n段区间，起始值、结束值是所有数据的最小值、最大值，用来划分区间
pd.cut(df1['salary'], bins=2)
# 4180~14100~24000
pd.cut(df1['salary'], bins=2).value_counts()
# Categories (3, interval[int64, right]):
# [(0, 10000] < (10000, 20000] < (20000, 30000]]
pd.cut(df1['salary'], bins=[0, 10000, 20000, 30000])  # bins = list ，分成len(list) -1 段
pd.cut(df1['salary'], bins=[0, 10000, 20000, 30000]).value_counts()
# Categories (3, str): ['低' < '中' < '高']
pd.cut(df1['salary'], bins=[0, 10000, 20000, 30000], labels=['低', '中', '高'])

0    高
1    中
2    中
3    低
4    低
5    低
6    低
7    低
8    中
9    低
Name: salary, dtype: category
Categories (3, str): ['低' < '中' < '高']

In [83]:
# 让每一段的人数相同,等频率分箱
pd.qcut(df1['salary'], 3).value_counts()

salary
(4199.999, 6000.0]    4
(6000.0, 12000.0]     3
(12000.0, 24000.0]    3
Name: count, dtype: int64

In [93]:
# 睡眠数据
df = pd.read_csv('data/sleep.csv')
# df
df1 = df.head(10)[['person_id', 'sleep_quality']]
df['睡眠质量'] = pd.cut(df1['sleep_quality'], bins=3, labels=['差', '中', '优'])
df.value_counts()

# 类型转换 分类类型
df['gender'] = df['gender'].astype('category')
df['gender'].value_counts()
# 字符串-》类别-〉统计
# 数值-》分箱-〉统计
print(df['睡眠质量'].dtype)  # category
print(df['gender'].dtype)  # category

category
category

In [102]:
# df.rename() df.set_index() df.reset_index()
df = pd.DataFrame({
    'name': ['alice', 'bob'],
    'age': [29, 23],
    'gender': ['female', 'male'],
})

df
# 设置索引
df.set_index('name', inplace=True)
df.reset_index(inplace=True)
df.rename(columns={'age': '年龄'}, index={0: 2})
df

    name  age  gender
0  alice   29  female
1    bob   23    male

In [111]:
# 时间数据的处理
import pandas as pd

d = pd.Timestamp('2015-05-02 10:22')  # 2015-05-02 10:22:00
print(d)
print(type(d))  #<class 'pandas.Timestamp'>
print(d.year)
print(d.month)
print(d.day)
print(d.hour)
print(d.minute)
print(d.second)
print('季度：', d.quarter)
print('是否是月底：', d.is_month_end)

# 方法
print('星期几：', d.day_name())
print('转换为天：', d.to_period('D'))  # 转换为天： 2015-05-02
print('转换为季度：', d.to_period('Q'))  # 转换为季度： 2015Q2
print('转换为年度：', d.to_period('Y'))  # 转换为年度： 2015
print('转换为月度：', d.to_period('M'))  # 转换为月度： 2015-05
print('转换为周维度：', d.to_period('W'))  # 转换为周维度： 2015-04-27/2015-05-03

2015-05-02 10:22:00
<class 'pandas.Timestamp'>
2015
5
2
10
22
0
季度： 2
是否是月底： False
星期几： Saturday
转换为天： 2015-05-02
转换为季度： 2015Q2
转换为年度： 2015
转换为月度： 2015-05
转换为周维度： 2015-04-27/2015-05-03

In [132]:
# 字符串转换为日期类型
# a = pd.to_datetime('2015-05-02 10:22')
# # a = pd.to_datetime('2015-05-02')
# # a = pd.to_datetime('20150502')
# print(a)
# print(type(a))  # <class 'pandas.Timestamp'>
# print(a.day_name())  # Saturday

# dataFrame 日期转换

df = pd.DataFrame({
    'sales': [100, 200, 300],
    'date': ['20150502', '20150503', '20150504'],
})
df['datetime']= pd.to_datetime(df['date'])
df
print(df.info())
# 注意：在dataFrame中需要使用dt选择
print(df['datetime'].dt.day_name())

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sales     3 non-null      int64
 1   date      3 non-null      str
 2   datetime  3 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 204.0 bytes
None
0    Saturday
1      Sunday
2      Monday
Name: datetime, dtype: str

In [135]:
# csv 日期转换
# 因为日期转换基本是非常常见的，可以在读入数据传参
# df = pd.read_csv('data/weather.csv', parse_dates=['date'])
df = pd.read_csv('data/weather.csv')
print(df)
df.info() # 0   date           1461 non-null   str
df['datetime'] = pd.to_datetime(df['date'])
df.info() # 6   datetime       1461 non-null   datetime64[us]
df['datetime'].dt.day_name()

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]
<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   str
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: float64(4), str(2)
memory usage: 68.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   str
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
 6   datetime       1461 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(4), str(2)
memory usage: 80.0 KB

In [141]:
# 日期数据作为索引
df.set_index('datetime', inplace=True) # 设置原来的df索引
print(df.loc['2013-05-02':'2015-05-03'])

            precipitation  temp_max  temp_min  wind weather
datetime
2013-05-02            0.0      20.6       6.7   4.0     sun
2013-05-03            0.0      21.7       9.4   4.9     sun
2013-05-04            0.0      25.0      11.1   6.5     sun
2013-05-05            0.0      28.9      11.7   5.3     sun
2013-05-06            0.0      30.6      12.2   2.0     sun
...                   ...       ...       ...   ...     ...
2015-04-29            0.0      16.1       7.2   4.7     sun
2015-04-30            0.0      17.2       7.8   2.1     sun
2015-05-01            0.0      18.3       8.9   3.7     sun
2015-05-02            0.0      18.3       7.8   3.7     sun
2015-05-03            0.0      20.6       7.8   2.6     sun

[732 rows x 5 columns]

In [143]:
# 时间间隔
d1 = pd.Timestamp('2013-05-02 10:22')
d2 = pd.Timestamp('2023-05-02 10:22')
d3 = d2 - d1
print(type(d3)) # 数据类型： <class 'pandas.Timedelta'>
print(d3) # 3652 days 00:00:00

<class 'pandas.Timedelta'>
3652 days 00:00:00

In [152]:
df = pd.read_csv('data/weather.csv', parse_dates=['date'])
df.info()
# 计算时间间隔(date这一列和索引为0的时间间隔)
df['detla'] = df['date'] - df['date'][0]
print(df)
df.set_index('detla', inplace=True)

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[us]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 68.6 KB
           date  precipitation  temp_max  temp_min  wind  weather     detla
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle    0 days
1    2012-01-02           10.9      10.6       2.8   4.5     rain    1 days
2    2012-01-03            0.8      11.7       7.2   2.3     rain    2 days
3    2012-01-04           20.3      12.2       5.6   4.7     rain    3 days
4    2012-01-05            1.3       8.9       2.8   6.1     rain    4 days
...         ...            ...       ...       ...   ...      ...       ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain 1456 days
1457 2015-12-28            1.5       5.0       1.7   1.3     rain 1457 days
1458 2015-12-29            0.0       7.2       0.6   2.6      fog 1458 days
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun 1459 days
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun 1460 days

[1461 rows x 7 columns]

In [156]:
df
#  进行切片
print(df.loc['10 days':'20 days'])

          date  precipitation  temp_max  temp_min  wind weather    detla
2   2012-01-03            0.8      11.7       7.2   2.3    rain   2 days
3   2012-01-04           20.3      12.2       5.6   4.7    rain   3 days
4   2012-01-05            1.3       8.9       2.8   6.1    rain   4 days
5   2012-01-06            2.5       4.4       2.2   2.2    rain   5 days
6   2012-01-07            0.0       7.2       2.8   2.3    rain   6 days
..         ...            ...       ...       ...   ...     ...      ...
195 2012-07-14            0.0      25.0      15.0   2.2    rain 195 days
196 2012-07-15            0.0      18.9      13.3   3.8    rain 196 days
197 2012-07-16            0.3      26.1      13.3   2.5    rain 197 days
198 2012-07-17            0.0      21.7      15.0   2.6     sun 198 days
199 2012-07-18            0.0      21.1      14.4   2.9     sun 199 days

[198 rows x 7 columns]

In [158]:
# 创建一个时间序列
days = pd.date_range('2025-07-03','2025-07-30', freq='D')
days = pd.date_range('2025-07-03',periods=10, freq='W')
print(days)

DatetimeIndex(['2025-07-06', '2025-07-13', '2025-07-20', '2025-07-27',
               '2025-08-03', '2025-08-10', '2025-08-17', '2025-08-24',
               '2025-08-31', '2025-09-07'],
              dtype='datetime64[us]', freq='W-SUN')

In [167]:
df = pd.read_csv('data/weather.csv', parse_dates=['date'])
# df.info()
df.set_index('date', inplace=True)

# 重新采样
# 返回一个DataFrame，按照年结束时间
df1 = df[['temp_max','temp_min']].resample('YE').mean()
print(df1)

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616

In [168]:
df1 = df[['temp_max','temp_min']].resample('YS').mean()
df1 = df[['temp_max','temp_min']].resample('MS').mean()
df1 = df[['temp_max','temp_min']].resample('QS').mean()

In [184]:
# 分组聚合（用来统计）
# df.groupby('分组的字段')['聚合的字段'].聚合函数()
import pandas as pd
df = pd.read_csv('data/employees.csv')
# print(df)
# 先处理缺失值
df['department_id'].isna().sum()
df.dropna(subset=['department_id'], inplace=True)
df['department_id'] = df['department_id'].astype('int64')

# 计算不同部门的平均薪资
df.groupby('department_id').groups # 查看分组
df.groupby('department_id').get_group(10) # 查看具体的某个分组数据
# <pandas.api.typing.SeriesGroupBy object at 0x10a7bb3e0>
# 类似 select sum(salary),department_id from employee group by department_id
# df.groupby('department_id')[['salary']].mean()
df2 = df.groupby('department_id')[['salary']].mean()
df2['salary'] = df2['salary'].round(2)
print(df2)
df2 = df2.reset_index()
df2.sort_values('salary', ascending=False, inplace=True)

                 salary
department_id
10              4400.00
20              9500.00
30              4150.00
40              6500.00
50              3475.56
60              5760.00
70             10000.00
80              8955.88
90             19333.33
100             8600.00
110            10150.00

In [187]:
# 计算不同部门不同岗位的人的平均薪资
df2 = df.groupby(['department_id','job_id'])[['salary']].mean()
df2['salary'] = df2['salary'].round(2)
df2 = df2.reset_index()
df2.sort_values('salary', ascending=False, inplace=True)
print(df2)

    department_id      job_id    salary
13             90     AD_PRES  24000.00
14             90       AD_VP  17000.00
1              20      MK_MAN  13000.00
11             80      SA_MAN  12200.00
18            110      AC_MGR  12000.00
16            100      FI_MGR  12000.00
4              30      PU_MAN  11000.00
10             70      PR_REP  10000.00
12             80      SA_REP   8396.55
17            110  AC_ACCOUNT   8300.00
15            100  FI_ACCOUNT   7920.00
8              50      ST_MAN   7280.00
5              40      HR_REP   6500.00
2              20      MK_REP   6000.00
9              60     IT_PROG   5760.00
0              10     AD_ASST   4400.00
6              50    SH_CLERK   3215.00
7              50    ST_CLERK   2785.00
3              30    PU_CLERK   2780.00

In [1]:
# 企鹅数据分析
# 1.导入必要的库
import pandas as pd
import numpy as np

# 2.导入分析的数据
df = pd.read_csv('data/penguins.csv')
df.head(5)
# print(df.head(5))
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [2]:
# 3.数据清洗
# 缺失值的检查
print(df.isna().sum())
df.dropna(inplace=True)
print(df.isna().sum())

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [3]:
# 4.数据特征的构造
df.head()
print(df.head())
df['sex'] = df['sex'].astype('category')
print(df.info())
df['bill_ratio'] = df['bill_length_mm'] / df['bill_depth_mm']
print(df.head())

  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0
1  Adelie  Torgersen            39.5           17.4              186.0
2  Adelie  Torgersen            40.3           18.0              195.0
4  Adelie  Torgersen            36.7           19.3              193.0
5  Adelie  Torgersen            39.3           20.6              190.0

   body_mass_g     sex
0       3750.0    Male
1       3800.0  Female
2       3250.0  Female
4       3450.0  Female
5       3650.0    Male
<class 'pandas.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    str
 1   island             333 non-null    str
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    category
dtypes: category(1), float64(4), str(2)
memory usage: 18.6 KB
None
  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0
1  Adelie  Torgersen            39.5           17.4              186.0
2  Adelie  Torgersen            40.3           18.0              195.0
4  Adelie  Torgersen            36.7           19.3              193.0
5  Adelie  Torgersen            39.3           20.6              190.0

   body_mass_g     sex  bill_ratio
0       3750.0    Male    2.090909
1       3800.0  Female    2.270115
2       3250.0  Female    2.238889
4       3450.0  Female    1.901554
5       3650.0    Male    1.907767

In [4]:
# 5.数据分析
# 数据分箱 -体重分为三个等级
labels = ['低','中','高']
df['mass_level'] =pd.cut(df['body_mass_g'],bins=3,labels=labels)
print(df.head())
print(df['mass_level'].value_counts())

# 按照岛屿、性别分组分析
# 按照性别分组，计算体重的均值和计数
print('*' * 20)
df.groupby(['sex'])['body_mass_g'].agg(['mean', 'count'])
# df.groupby(['island', 'sex'])['body_mass_g'].agg(['mean', 'count'])
df.groupby(['island'])['body_mass_g'].agg(['mean', 'count'])

  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0
1  Adelie  Torgersen            39.5           17.4              186.0
2  Adelie  Torgersen            40.3           18.0              195.0
4  Adelie  Torgersen            36.7           19.3              193.0
5  Adelie  Torgersen            39.3           20.6              190.0

   body_mass_g     sex  bill_ratio mass_level
0       3750.0    Male    2.090909          低
1       3800.0  Female    2.270115          低
2       3250.0  Female    2.238889          低
4       3450.0  Female    1.901554          低
5       3650.0    Male    1.907767          低
mass_level
低    150
中    128
高     55
Name: count, dtype: int64
********************

                  mean  count
island
Biscoe     4719.171779    163
Dream      3718.902439    123
Torgersen  3708.510638     47

In [6]:
df.groupby(['island'])['body_mass_g'].agg(['mean', 'count'])

                  mean  count
island
Biscoe     4719.171779    163
Dream      3718.902439    123
Torgersen  3708.510638     47

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio,mass_level
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909,低
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115,低
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889,低
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554,低
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767,低
...,...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,3.445255,中
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,3.272727,中
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,3.210191,高
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,3.054054,高
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,3.099379,高

In [7]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio,mass_level
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909,低
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115,低
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889,低
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554,低
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767,低
...,...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,3.445255,中
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,3.272727,中
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,3.210191,高
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,3.054054,高
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,3.099379,高

In [ ]:
# 睡眠质量分析